# Generated by Django 5.1 on 2024-09-04 05:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_article_content_remove_article_ppoi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contact',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
